#==========================================================================
# Copyright 2025 IHP PDK Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# SPDX-License-Identifier: Apache-2.0
#==========================================================================

name: DRC regression testing

# Prevent keeping resources busy when a branch/PR is updated
# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - 'ihp-sg13g2/libs.tech/klayout/tech/drc/**'
  workflow_dispatch:

jobs:
  drc_regression:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Klayout
        run: |
          sudo apt update -qq -y
          # Download KLayout .deb using curl with retry options
          curl -L --retry 5 --retry-delay 5 -o klayout.deb https://www.klayout.org/downloads/Ubuntu-24/klayout_0.30.2-1_amd64.deb
          # The dpkg command will fail complaining about missing dependencies.
          sudo dpkg -i ./klayout.deb || true
          # The apt install command should install the missing dependencies
          # needed by KLayout above and finish the install.
          sudo apt install -f -y
          # Reinstall KLayout After Fixing Dependencies
          sudo dpkg -i ./klayout.deb || true
          # Check that KLayout was successfully installed!
          klayout -v

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Testing SG13G2 Klayout DRC Regression
        run: |
          make test-DRC-main
